### ISSUE TITLE
core/order/execution missing

### ISSUE THREAD

**Issue by mortensorensen** [cyanly/gotrade#4]
`orderbook.go`:

```
import (
        ...
	er "github.com/cyanly/gotrade/core/order/execution"
        ...
)
```

`core/order/execution` is missing from version control. Do you mind committing?

Thanks!

**Comment by hoathienvu8x** [comment]
Please check the repository https://github.com/iloginov/gotrade

**Comment by redthor** [comment]
fwiw same as https://github.com/cyanly/gotrade/issues/2#issuecomment-322104955
